# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @testim/testim-cli
    testim --name "demo demo demo" \
    --token "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjowLCJkIjp7InVpZCI6ImNpOjJpVGhiNmliIiwiZW1haWwiOiJnaWxAdGVzdGltLmlvIn0sImlhdCI6MTQ5NTAyMDUxOX0.DElAUsrn2j7Y7frEnoBgkxf5YpXuS5OWdxS1SZtD1sE" \
    --project "2iThb6ib" \
    --host "dev-grid.testim.io"  \
    --report-file testim-tests-report.xml
  displayName: 'npm install testim-cli and run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testim-tests-report.xml' 